name: 📦 Publish to candidate

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
    branches: [ "candidate" ]
  # Allow the workflow to be started manually from the Actions tab.
  workflow_dispatch:
  # Allow the workflow to be started by another workflow.
  workflow_call:
    secrets:
      SNAP_STORE_CANDIDATE:
        required: true
      LP_BUILD_SECRET:
        required: true

# Permissions for GITHUB_TOKEN
permissions:
  contents: read
  issues: write

env:
  # Use the name of the repo as the name of the snap
  SNAP_NAME: ${{ github.event.repository.name }}
  # Hardcoded git branch and Snap Store channel channel
  CHANNEL: 'candidate'

jobs:
  build:
    name: "Build & publish"
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ['amd64', 'arm64']
    outputs:
      revision_amd64: ${{ steps.publish.outputs.revision_amd64 }}
      revision_arm64: ${{ steps.publish.outputs.revision_arm64 }}
      version: ${{ steps.build.outputs.version }}
    steps:
      - name: Checkout the source
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHANNEL }}

      - name: Setup snapcraft
        env:
          LP_BUILD_SECRET: ${{ secrets.LP_BUILD_SECRET }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_CANDIDATE }}
        run: |
          sudo snap install snapcraft --classic
          
          # Setup Launchpad credentials
          mkdir -p ~/.local/share/snapcraft/provider/launchpad
          echo "$LP_BUILD_SECRET" > ~/.local/share/snapcraft/provider/launchpad/credentials
          git config --global user.email "github-actions@github.com"
          git config --global user.name "Github Actions"

      - name: Remote build the snap
        id: build
        env:
          ARCHITECTURE: ${{ matrix.architecture }}
        run : |
          snapcraft remote-build --launchpad-accept-public-upload --build-for=${ARCHITECTURE}

          version="$(cat snap/snapcraft.yaml | yq -r '.version')"
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "snap=signal-desktop_${version}_${ARCHITECTURE}.snap" >> "$GITHUB_OUTPUT"

      - name: Review the built snap
        uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: 'false'

      - name: Publish the built snap
        id: publish
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_CANDIDATE }}
          SNAP_NAME: ${{ steps.build.outputs.snap }}
          ARCHITECTURE: ${{ matrix.architecture }}
        run: |
          rev=$(snapcraft push $SNAP_NAME --release=$CHANNEL)
          echo "revision_${ARCHITECTURE}=${rev}" >> $GITHUB_OUTPUT

  # Create an issue using the template that asks maintainers to test the snap, and take
  # action to promote the revisions to stable if testing is successful.
  create_issue:
    name: "Create call for testing"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        id: comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          revision_amd64: ${{ needs.build.outputs.revision_amd64 }}
          revision_arm64: ${{ needs.build.outputs.revision_arm64 }}
          version: ${{ needs.build.outputs.version }}
        with:
          filename: .github/testing-issue-template.md
    outputs:
      issue_number: ${{ steps.comment.outputs.number }}

  # Deploy the snap inside a desktop VM and grab screenshots of the desktop, and of
  # the application, then post them as a comment on the issue created above.
  grab-screenshots:
    name: Gather screenshots
    needs: 
      - build
      - create_issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1

      - name: Setup test machine and start Signal
        id: screenshots
        run: |
          .github/vmctl prepare
          .github/vmctl exec "sudo snap install ${{ env.SNAP_NAME }} --revision ${{ needs.build.outputs.revision_amd64 }}"
          .github/vmctl exec "snap run signal-desktop &>/home/ubuntu/signal.log &"
          sleep 20

          screenshot_full="$(.github/vmctl screenshot-full)"
          echo "Screenshot of full screen at: $screenshot_screen"
          echo "screen=$screenshot_full" >> "$GITHUB_OUTPUT"

          screenshot_window="$(.github/vmctl screenshot-window)"
          echo "Screenshot of window at: $screenshot_window"
          echo "window=$screenshot_window" >> "$GITHUB_OUTPUT"

          # Output the Signal logs captured from stdout/stderr (for debgging if required)
          .github/vmctl exec "cat /home/ubuntu/signal.log"

      - name: Comment on call for testing issue with screenshots
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ needs.create_issue.outputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The following screenshots were taken during automated testing:

              ![window](${{ steps.screenshots.outputs.window }})

              ![screen](${{ steps.screenshots.outputs.screen }})
              `
            })
